services:
    auth.provider.oauth.service.evesso:
        class: imperialdreams\evesso\core\evesso
        arguments:
            - '@config'
            - '@request'
        tags:
            - { name: auth.provider.oauth.service }